auth:
    allow_registration: false
    jwt_expiry: 24h0m0s
    jwt_secret: grape-secret-key-change-in-production
database:
    dsn: ./data/grape.db
    type: sqlite
log:
    level: info
registry:
    upstream: https://registry.npmjs.org
    upstreams:
        - enabled: true
          name: npmjs
          scope: ""
          timeout: 30s
          url: https://registry.npmjs.org
        - enabled: true
          name: npmmirror
          scope: ""
          timeout: 15s
          url: https://registry.npmmirror.com
server:
    host: 0.0.0.0
    port: 4873
    api_port: 4874
    read_timeout: 30s
    write_timeout: 30s
storage:
    path: ./data
    type: local
